### ISSUE TITLE
Allow importing configuration via QR code

### ISSUE THREAD

**Issue by petitJAM** [petitJAM/Spider#12]
Write a Ruby script for turning a YAML file into a QR code image.

```
url: 'www.example.com'
protocol: 'https'
headers:
  header:
    name: 'X-Whatever-Header'
    value: 'some_val'
```
